stages:
  - build

build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/dgyurics/idea-webapp .
    - docker push registry.gitlab.com/dgyurics/idea-webapp
