export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const GET_IDEAS_REQUEST = 'GET_IDEAS_REQUEST'
export const GET_IDEAS_SUCCESS = 'GET_IDEAS_SUCCESS'
export const GET_IDEAS_FAILURE = 'GET_IDEAS_FAILURE'

export const CREATE_IDEA_REQUEST = 'CREATE_IDEA_REQUEST'
export const CREATE_IDEA_SUCCESS = 'CREATE_IDEA_SUCCESS'
export const CREATE_IDEA_FAILURE = 'CREATE_IDEA_FAILURE'

export const GET_CONVERSATION_REQUEST = 'GET_CONVERSATION_REQUEST'
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATION_SUCCESS'
export const GET_CONVERSATION_FAILURE = 'GET_CONVERSATION_FAILURE'

export const CREATE_MESSAGE_REQUEST = 'CREATE_MESSAGE_REQUEST'
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS'
export const CREATE_MESSAGE_FAILURE = 'CREATE_MESSAGE_FAILURE'
