export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const REGISTRATION_PENDING = 'REGISTRATION_PENDING';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';

export const FORGOT_PASSWORD_PENDING = 'FORGOT_PASSWORD_PENDING';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

export const VALIDATE_RESET_CODE_PENDING = 'VALIDATE_RESET_CODE_PENDING';
export const VALIDATE_RESET_CODE_SUCCESS = 'VALIDATE_RESET_CODE_SUCCESS';
export const VALIDATE_RESET_CODE_FAIL = 'VALIDATE_RESET_CODE_FAIL';

export const UPDATE_PASSWORD_PENDING = 'UPDATE_PASSWORD_PENDING';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';

export const LOAD_LOCAL_JWT_PENDING = 'LOAD_LOCAL_JWT_PENDING';
export const LOAD_LOCAL_JWT_SUCCESS = 'LOAD_LOCAL_JWT_SUCCESS';
export const LOAD_LOCAL_JWT_FAIL = 'LOAD_LOCAL_JWT_FAIL';
export const LOAD_LOCAL_JWT_EXPIRED = 'LOAD_LOCAL_JWT_EXPIRED';

export const REFRESH_JWT_PENDING = 'REFRESH_JWT_PENDING';
export const REFRESH_JWT_SUCCESS = 'REFRESH_JWT_SUCCESS';
export const REFRESH_JWT_FAIL = 'REFRESH_JWT_FAIL';

export const TOGGLE_HELP_MODAL = 'TOGGLE_HELP_MODAL';
export const TOGGLE_REGISTRATION_MODAL = 'TOGGLE_REGISTER_MODAL';
export const TOGGLE_FORGOT_PASSWORD_MODAL = 'TOGGLE_FORGOT_PASSWORD_MODAL';
export const TOGGLE_RESET_CODE_MODAL = 'TOGGLE_RESET_CODE_MODAL';
export const TOGGLE_NEW_PASSWORD_MODAL = 'TOGGLE_NEW_PASSWORD_MODAL';
export const TOGGLE_SUCCESS_MODAL = 'TOGGLE_SUCCESS_MODAL';
