export const GET_BOOKS_PENDING = 'GET_BOOKS_PENDING';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_FAIL = 'GET_BOOKS_FAIL';

export const ADD_BOOK_PENDING = 'ADD_BOOK_PENDING';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL';

export const REMOVE_BOOK_PENDING = 'REMOVE_BOOK_PENDING';
export const REMOVE_BOOK_SUCCESS = 'REMOVE_BOOK_SUCCESS';
export const REMOVE_BOOK_FAIL = 'REMOVE_BOOK_FAIL';

export const TOGGLE_BOOK_MODAL = 'TOGGLE_BOOK_MODAL';
export const TOGGLE_ADD_BOOK_MODAL = 'TOGGLE_ADD_BOOK_MODAL';
export const TOGGLE_REMOVE_BOOK_MODAL = 'TOGGLE_REMOVE_BOOK_MODAL';
export const TOGGLE_SUCCESS_MODAL = 'TOGGLE_SUCCESS_MODAL';
