export const CONTACT_US_PENDING = 'CONTACT_US_PENDING';
export const CONTACT_US_SUCCESS = 'CONTACT_US_SUCCESS';
export const CONTACT_US_FAIL = 'CONTACT_US_FAIL';
export const TOGGLE_FORM = 'TOGGLE_FORM';
